from datetime import datetime, timezone

clusters = {
    0: {
        "event_tweets": [
            {
                "id": 181594,
                "status_id_str": "1",
                "user_id_str": "12301",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 23, 33, 22, tzinfo=timezone.utc),
                "user_screen_name": "user12301",
                "tweet_body": (
                    "Time in a ballpark does not count against your natural lifespan."
                    " #RedSox https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181539,
                "status_id_str": "2",
                "user_id_str": "12302",
                "deleted_at": None,
                "tweet_language": "ja",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 21, 13, 19, tzinfo=timezone.utc),
                "user_screen_name": "user12302_2_tweets",
                "tweet_body": (
                    "今日はボストンでレッドソックス対ブルージェイズ戦。菊池雄星投手が今季2度目の先発。And a legendary"
                    " @DavidLaurilaQA is interviewing @GosukeKatoh. #bluejays"
                    " https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 0.1353352832366127,
            },
            {
                "id": 181584,
                "status_id_str": "3",
                "user_id_str": "12302",
                "deleted_at": None,
                "tweet_language": "ja",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 23, 12, 11, tzinfo=timezone.utc),
                "user_screen_name": "user12302_2_tweets",
                "tweet_body": (
                    "ブルージェイズ対レッドソックス戦始まります。菊池雄星投手、新天地での初勝利なるか。加藤豪将選手、沢村拓一投手の出番はあるかどうか。"
                    " https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 0.018315638888734182,
            },
            {
                "id": 181491,
                "status_id_str": "4",
                "user_id_str": "12303",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 19, 33, 4, tzinfo=timezone.utc),
                "user_screen_name": "user12303_2_tweets",
                "tweet_body": "Oh hey 👋 https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181500,
                "status_id_str": "5",
                "user_id_str": "12303",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 19, 57, 45, tzinfo=timezone.utc),
                "user_screen_name": "user12303_2_tweets",
                "tweet_body": (
                    "Toronto\nBoston\nNew York\nTampa Bay\nBaltimore\n\nBig if true."
                    " https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 0.1353352832366127,
            },
            {
                "id": 181567,
                "status_id_str": "6",
                "user_id_str": "12304",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.346424,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 22, 40, 23, tzinfo=timezone.utc),
                "user_screen_name": "user12304",
                "tweet_body": (
                    "At Fenway Park for my first MLB game since before the pandemic"
                    " getting ready to watch the @RedSox take on the Blue Jays #RedSox"
                    " #MLB https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181551,
                "status_id_str": "7",
                "user_id_str": "12305",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 21, 57, 8, tzinfo=timezone.utc),
                "user_screen_name": "user12305",
                "tweet_body": "Back at my happy place. https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181561,
                "status_id_str": "8",
                "user_id_str": "12306",
                "deleted_at": None,
                "tweet_language": "und",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 22, 23, 31, tzinfo=timezone.utc),
                "user_screen_name": "user12306",
                "tweet_body": "👀⚾️✔️ https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181580,
                "status_id_str": "9",
                "user_id_str": "12307",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 23, 8, 47, tzinfo=timezone.utc),
                "user_screen_name": "user12307",
                "tweet_body": "I’ve missed Fenway nights ❤️❤️❤️ https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181484,
                "status_id_str": "10",
                "user_id_str": "12308",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 19, 25, 36, tzinfo=timezone.utc),
                "user_screen_name": "user12308_2_tweets",
                "tweet_body": "Flow looking 💯 today https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181520,
                "status_id_str": "11",
                "user_id_str": "12308",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.346424,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 20, 38, 35, tzinfo=timezone.utc),
                "user_screen_name": "user12308_2_tweets",
                "tweet_body": (
                    "Skies are looking a bit threatening, but we are very much ready to"
                    " see the Blue Jays irl for the first time since 2019 🤩"
                    " https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 0.1353352832366127,
            },
            {
                "id": 181443,
                "status_id_str": "12",
                "user_id_str": "12309",
                "deleted_at": None,
                "tweet_language": "und",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 17, 53, 15, tzinfo=timezone.utc),
                "user_screen_name": "user12309",
                "tweet_body": "😎 https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181598,
                "status_id_str": "13",
                "user_id_str": "12310",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.346424,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 23, 37, 30, tzinfo=timezone.utc),
                "user_screen_name": "user12310",
                "tweet_body": (
                    "My first conference talk I'm person in two years, coupled with my"
                    " first @RedSox and bumping into @Leonora_Abd! Been a great"
                    " conference so far! https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181394,
                "status_id_str": "14",
                "user_id_str": "12311",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 15, 15, 18, tzinfo=timezone.utc),
                "user_screen_name": "user12311",
                "tweet_body": "Current View.\nOutside @fenwaypark. https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181596,
                "status_id_str": "15",
                "user_id_str": "12312",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 23, 34, 23, tzinfo=timezone.utc),
                "user_screen_name": "user12312",
                "tweet_body": (
                    "Obviously in the house for former Seibu Lions starter Yusei"
                    " Kikuchi vs the Red Sox tonight 🤩 https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181524,
                "status_id_str": "16",
                "user_id_str": "12313",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 20, 47, 4, tzinfo=timezone.utc),
                "user_screen_name": "user12313",
                "tweet_body": (
                    "Got laughed at when I compared baseball to rounders ⚾️⚾️⚾️ #RedSox"
                    " #fenwaypark #Boston https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181517,
                "status_id_str": "17",
                "user_id_str": "12314",
                "deleted_at": None,
                "tweet_language": "ja",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 20, 34, 56, tzinfo=timezone.utc),
                "user_screen_name": "user12314_2_tweets",
                "tweet_body": (
                    "マラソンから #fenwaypark に流れてきました🏃\u200d♂️⚾️ https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": True,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181519,
                "status_id_str": "18",
                "user_id_str": "12314",
                "deleted_at": None,
                "tweet_language": "ja",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 20, 36, 43, tzinfo=timezone.utc),
                "user_screen_name": "user12314_2_tweets",
                "tweet_body": "ブルージェイズの菊池雄星投手がレッドソックス戦に先発予定です https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": True,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 0.1353352832366127,
            },
            {
                "id": 181566,
                "status_id_str": "19",
                "user_id_str": "12315",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 22, 40, 1, tzinfo=timezone.utc),
                "user_screen_name": "user12315",
                "tweet_body": "Reading y’all from here https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
            {
                "id": 181326,
                "status_id_str": "20",
                "user_id_str": "12316",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.34642,
                "place_name": "Fenway Park",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 11, 55, 39, tzinfo=timezone.utc),
                "user_screen_name": "user12316",
                "tweet_body": "Why not #bostonmarathon126 #RedSox https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.09816,
                "place_id": "0fc2e91c5e94d001",
                "weight": 1.0,
            },
        ]
    },
    1: {
        "event_tweets": [
            {
                "id": 181183,
                "status_id_str": "101",
                "user_id_str": "123101",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 18, 23, 52, 10, tzinfo=timezone.utc),
                "user_screen_name": "user123101",
                "tweet_body": "Boston was a major success 🤘🏽 https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 1.0,
            },
            {
                "id": 181188,
                "status_id_str": "102",
                "user_id_str": "123102",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 0, 0, 54, tzinfo=timezone.utc),
                "user_screen_name": "user123102",
                "tweet_body": (
                    "Two years in a row! 🎉\n\nMarathon Coverage? \nHere for"
                    " it.\n\nRunning?\nNot so much.😉\n\nCongratulations to all of the"
                    " incredible people that reached 26.2 today. You’re all"
                    " amazing!\n\n#Boston25 https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 1.0,
            },
            {
                "id": 181341,
                "status_id_str": "103",
                "user_id_str": "123102",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 12, 40, 55, tzinfo=timezone.utc),
                "user_screen_name": "user123102_2_tweets",
                "tweet_body": (
                    "Two more of my favorites from yesterday’s @bostonmarathon"
                    " coverage. 💛💙\n\nWhat an inspiring &amp; uplifting day!"
                    " https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 0.1353352832366127,
            },
            {
                "id": 181366,
                "status_id_str": "104",
                "user_id_str": "123103",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 14, 9, 4, tzinfo=timezone.utc),
                "user_screen_name": "user123103",
                "tweet_body": (
                    "@bostonmarathon it was nice to meet you! 👩🏽‍🚀 You were brutal but"
                    " amazing! #marathon #running https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 1.0,
            },
            {
                "id": 181409,
                "status_id_str": "105",
                "user_id_str": "123104",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 15, 57, 22, tzinfo=timezone.utc),
                "user_screen_name": "user123103",
                "tweet_body": (
                    "Dear Boston Marathon, it was nice to meet you! 👩🏽‍🚀 Your hills"
                    " were brutal but the crowd was amazing! #BostonMarathon #marathon"
                    " #running @bostonmarathon https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 0.1353352832366127,
            },
            {
                "id": 181193,
                "status_id_str": "106",
                "user_id_str": "123105",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 0, 10, 40, tzinfo=timezone.utc),
                "user_screen_name": "user123105",
                "tweet_body": (
                    "A great day 🤘🏽 with my forever running buddy and our little champ!"
                    " #BostonMarathon https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 1.0,
            },
            {
                "id": 181306,
                "status_id_str": "107",
                "user_id_str": "123106",
                "deleted_at": None,
                "tweet_language": "und",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 10, 29, 2, tzinfo=timezone.utc),
                "user_screen_name": "user123106",
                "tweet_body": "3:55:57 🙏🏾 https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 1.0,
            },
            {
                "id": 181323,
                "status_id_str": "108",
                "user_id_str": "123107",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 11, 42, 20, tzinfo=timezone.utc),
                "user_screen_name": "user123107",
                "tweet_body": (
                    "Congratulations @coryresnick for running @bostonmarathon great"
                    " work! @PlasticOralSurg @harvardmed https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 1.0,
            },
            {
                "id": 181242,
                "status_id_str": "109",
                "user_id_str": "123108",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 2, 1, 10, tzinfo=timezone.utc),
                "user_screen_name": "user123108",
                "tweet_body": (
                    "The most inspirational of days spent cheering on all of the"
                    " runners at the Boston Marathon and one in particular, Alex."
                    " #bostonmarathon2022 #inspirational https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 1.0,
            },
            {
                "id": 181192,
                "status_id_str": "110",
                "user_id_str": "123109",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 0, 9, 33, tzinfo=timezone.utc),
                "user_screen_name": "user123109",
                "tweet_body": (
                    "26.2 miles of smiles today at the @bostonmarathon! The weather,"
                    " the course &amp; the crowds..my ears are still ringing. \nI hoped"
                    " for a 4:30 race but managed a 3:58, something I never dreamt was"
                    " possible. I’ll be smiling about that for awhile. Thx for the"
                    " cheers &amp; THANK YOU BOSTON!🦄 https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 1.0,
            },
            {
                "id": 181184,
                "status_id_str": "111",
                "user_id_str": "123110",
                "deleted_at": None,
                "tweet_language": "en",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 18, 23, 53, 29, tzinfo=timezone.utc),
                "user_screen_name": "user123110",
                "tweet_body": (
                    "Great to meet you in person @davidwade !!! https://url.co/123"
                ),
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 1.0,
            },
            {
                "id": 181261,
                "status_id_str": "112",
                "user_id_str": "123111",
                "deleted_at": None,
                "tweet_language": "und",
                "is_reply_status": False,
                "has_coords": False,
                "latitude": 42.349842,
                "place_name": "Boston Marathon Finish Line",
                "place_type": "poi",
                "created_at": datetime(2022, 4, 19, 3, 5, 32, tzinfo=timezone.utc),
                "user_screen_name": "user123111",
                "tweet_body": "https://url.co/123",
                "is_quote_status": False,
                "possibly_sensitive": False,
                "longitude": -71.07869,
                "place_id": "0a64b7478dd66000",
                "weight": 1.0,
            },
        ]
    },
}
